// Dhanoka product catalog — seed data
// Add a new product by adding one object here (and its image in /assets/products/).
const DHANOKA_PRODUCTS = [
  {
    "id": "polin",
    "name": "Polin",
    "brand": "",
    "category": "",
    "image": "assets/products/polin.jpg",
    "packSizes": [
      "100 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "kinzan",
    "name": "Kinzan",
    "brand": "",
    "category": "",
    "image": "assets/products/kinzan.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "400 ml",
      "500 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "oxykill",
    "name": "OXYKILL",
    "brand": "",
    "category": "",
    "image": "assets/products/oxykill.jpg",
    "packSizes": [
      "50 ml",
      "100 ml",
      "250 ml",
      "500 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "d-era",
    "name": "D-Era",
    "brand": "",
    "category": "",
    "image": "assets/products/d-era.jpg",
    "packSizes": [
      "100 gm",
      "500 gm",
      "1 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "melody-duo",
    "name": "Melody Duo",
    "brand": "",
    "category": "",
    "image": "assets/products/melody-duo.jpg",
    "packSizes": [
      "250 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "turmoil",
    "name": "Turmoil",
    "brand": "",
    "category": "",
    "image": "assets/products/turmoil.jpg",
    "packSizes": [
      "250 ml",
      "500 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "dinkar",
    "name": "Dinkar",
    "brand": "",
    "category": "",
    "image": "assets/products/dinkar.jpg",
    "packSizes": [
      "100 ml",
      "200 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "markar-super",
    "name": "Markar Super",
    "brand": "",
    "category": "",
    "image": "assets/products/markar-super.jpg",
    "packSizes": [
      "500 ml",
      "1 l",
      "5 l"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "markar",
    "name": "Markar",
    "brand": "",
    "category": "",
    "image": "assets/products/markar.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "aaatank",
    "name": "Aaatank",
    "brand": "",
    "category": "",
    "image": "assets/products/aaatank.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "foster",
    "name": "Foster",
    "brand": "",
    "category": "",
    "image": "assets/products/foster.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "targa-super",
    "name": "Targa Super",
    "brand": "",
    "category": "",
    "image": "assets/products/targa-super.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "lustre",
    "name": "Lustre",
    "brand": "",
    "category": "",
    "image": "assets/products/lustre.jpg",
    "packSizes": [
      "100 ml",
      "384 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "myconxt",
    "name": "Myconxt",
    "brand": "",
    "category": "",
    "image": "assets/products/myconxt.jpg",
    "packSizes": [
      "100 gm"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "omninxt",
    "name": "Omninxt",
    "brand": "",
    "category": "",
    "image": "assets/products/omninxt.jpg",
    "packSizes": [
      "100 gm"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "downil",
    "name": "Downil",
    "brand": "",
    "category": "",
    "image": "assets/products/downil.jpg",
    "packSizes": [
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "sporenil",
    "name": "Sporenil",
    "brand": "",
    "category": "",
    "image": "assets/products/sporenil.jpg",
    "packSizes": [
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "whiteaxe",
    "name": "Whiteaxe",
    "brand": "",
    "category": "",
    "image": "assets/products/whiteaxe.jpg",
    "packSizes": [
      "1 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "nemataxe",
    "name": "Nemataxe",
    "brand": "",
    "category": "",
    "image": "assets/products/nemataxe.jpg",
    "packSizes": [
      "1 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "wetcit",
    "name": "Wetcit",
    "brand": "",
    "category": "",
    "image": "assets/products/wetcit.jpg",
    "packSizes": [
      "15 ml",
      "50 ml",
      "100 ml",
      "250 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "mycore-super",
    "name": "Mycore Super",
    "brand": "",
    "category": "",
    "image": "assets/products/mycore-super.jpg",
    "packSizes": [
      "4 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "mycore",
    "name": "Mycore",
    "brand": "",
    "category": "",
    "image": "assets/products/mycore.jpg",
    "packSizes": [
      "4 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "dhanzyme-gold-liq",
    "name": "Dhanzyme Gold Liquid",
    "brand": "",
    "category": "",
    "image": "assets/products/dhanzyme-gold-liq.jpg",
    "packSizes": [
      "15 ml",
      "100 ml",
      "250 ml",
      "500 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "dhanzyme-gold-granules",
    "name": "Dhanzyme Gold Granules",
    "brand": "",
    "category": "",
    "image": "assets/products/dhanzyme-gold-granules.jpg",
    "packSizes": [
      "5 kg",
      "10 kg",
      "25 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "dhanvarsha",
    "name": "Dhanvarsha",
    "brand": "",
    "category": "",
    "image": "assets/products/dhanvarsha.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "maxyld",
    "name": "Maxyld",
    "brand": "",
    "category": "",
    "image": "assets/products/maxyld.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "suelo",
    "name": "Suelo",
    "brand": "",
    "category": "",
    "image": "assets/products/suelo.jpg",
    "packSizes": [
      "250 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "miyako",
    "name": "Miyako",
    "brand": "",
    "category": "",
    "image": "assets/products/miyako.jpg",
    "packSizes": [],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "lanevo",
    "name": "Lanevo",
    "brand": "",
    "category": "",
    "image": "assets/products/lanevo.jpg",
    "packSizes": [],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "decide",
    "name": "Decide",
    "brand": "",
    "category": "",
    "image": "assets/products/decide.jpg",
    "packSizes": [],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "zapac",
    "name": "Zapac",
    "brand": "",
    "category": "",
    "image": "assets/products/zapac.jpg",
    "packSizes": [
      "80 ml",
      "200 ml",
      "500 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "ripple",
    "name": "Ripple",
    "brand": "",
    "category": "",
    "image": "assets/products/ripple.jpg",
    "packSizes": [
      "50 gm",
      "250 gm",
      "500 gm"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "jackal",
    "name": "Jackal",
    "brand": "",
    "category": "",
    "image": "assets/products/jackal.jpg",
    "packSizes": [
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "dhanpreet",
    "name": "Dhanpreet",
    "brand": "",
    "category": "",
    "image": "assets/products/dhanpreet.jpg",
    "packSizes": [
      "20 gm",
      "50 gm",
      "100 gm",
      "250 gm"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "media",
    "name": "Media",
    "brand": "",
    "category": "",
    "image": "assets/products/media.jpg",
    "packSizes": [
      "50 ml",
      "100 ml",
      "250 ml",
      "500 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "dhanulux",
    "name": "Dhanulux",
    "brand": "",
    "category": "",
    "image": "assets/products/dhanulux.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "deva-shakti",
    "name": "Deva Shakti",
    "brand": "",
    "category": "",
    "image": "assets/products/deva-shakti.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "superkiller-10",
    "name": "Superkiller 10% EC",
    "brand": "",
    "category": "",
    "image": "assets/products/superkiller-10pct-ec.jpg",
    "packSizes": [
      "50 ml",
      "100 ml",
      "250 ml",
      "500 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "superkiller-25",
    "name": "Superkiller 25% EC",
    "brand": "",
    "category": "",
    "image": "assets/products/superkiller-25pct-ec.jpg",
    "packSizes": [
      "50 ml",
      "100 ml",
      "250 ml",
      "500 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "caldan-50-sp",
    "name": "Caldan 50 SP",
    "brand": "",
    "category": "",
    "image": "assets/products/caldan-50-sp.jpg",
    "packSizes": [
      "50 gm",
      "100 gm",
      "250 gm",
      "500 gm"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "caldan-4g",
    "name": "Caldan 4G",
    "brand": "",
    "category": "",
    "image": "assets/products/caldan-4g.jpg",
    "packSizes": [
      "1 kg",
      "5 kg",
      "7.5 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "pager",
    "name": "Pager",
    "brand": "",
    "category": "",
    "image": "assets/products/pager.jpg",
    "packSizes": [
      "250 gm",
      "500 gm",
      "1 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "cover-liq",
    "name": "Cover Liq",
    "brand": "",
    "category": "",
    "image": "assets/products/cover-liq.jpg",
    "packSizes": [
      "10 ml",
      "30 ml",
      "60 ml",
      "150 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "cover-gr",
    "name": "Cover GR",
    "brand": "",
    "category": "",
    "image": "assets/products/cover-gr.jpg",
    "packSizes": [
      "4 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "omite",
    "name": "Omite",
    "brand": "",
    "category": "",
    "image": "assets/products/omite.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "media-super",
    "name": "Media Super",
    "brand": "",
    "category": "",
    "image": "assets/products/media-super.jpg",
    "packSizes": [
      "50 ml",
      "100 ml",
      "250 ml",
      "500 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "largo",
    "name": "Largo",
    "brand": "",
    "category": "",
    "image": "assets/products/largo.jpg",
    "packSizes": [
      "20 ml",
      "100 ml",
      "180 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "apply",
    "name": "Apply",
    "brand": "",
    "category": "",
    "image": "assets/products/apply.jpg",
    "packSizes": [
      "120 gm",
      "250 gm",
      "500 gm",
      "1 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "areva-super",
    "name": "Areva Super",
    "brand": "",
    "category": "",
    "image": "assets/products/areva-super.jpg",
    "packSizes": [
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "em-1",
    "name": "EM-1",
    "brand": "",
    "category": "",
    "image": "assets/products/em-1.jpg",
    "packSizes": [
      "10 gm",
      "50 gm",
      "100 gm",
      "250 gm"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "areva",
    "name": "Areva",
    "brand": "",
    "category": "",
    "image": "assets/products/areva.jpg",
    "packSizes": [
      "5 gm",
      "100 gm",
      "250 gm",
      "500 gm"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "ad-fyre",
    "name": "Ad-fyre",
    "brand": "",
    "category": "",
    "image": "assets/products/ad-fyre.jpg",
    "packSizes": [
      "16 gm",
      "30 gm",
      "75 gm",
      "150 gm"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "fax-sc",
    "name": "Fax SC",
    "brand": "",
    "category": "",
    "image": "assets/products/fax-sc.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "d-one",
    "name": "D-One",
    "brand": "",
    "category": "",
    "image": "assets/products/d-one.jpg",
    "packSizes": [
      "75 ml",
      "150 ml",
      "500 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "mortar",
    "name": "Mortar",
    "brand": "",
    "category": "",
    "image": "assets/products/mortar.jpg",
    "packSizes": [
      "100 gm",
      "250 gm",
      "500 gm",
      "1 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "delight",
    "name": "Delight",
    "brand": "",
    "category": "",
    "image": "assets/products/delight.jpg",
    "packSizes": [
      "100 gm",
      "500 gm"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "zanet",
    "name": "Zanet",
    "brand": "",
    "category": "",
    "image": "assets/products/zanet.jpg",
    "packSizes": [
      "100 ml",
      "400 ml",
      "1 litre"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "nissodium",
    "name": "Nissodium",
    "brand": "",
    "category": "",
    "image": "assets/products/nissodium.jpg",
    "packSizes": [
      "60 ml",
      "120 ml",
      "200 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "kirari",
    "name": "Kirari",
    "brand": "",
    "category": "",
    "image": "assets/products/kirari.jpg",
    "packSizes": [
      "75 ml",
      "150 ml",
      "200 ml",
      "500 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "zerox",
    "name": "Zerox",
    "brand": "",
    "category": "",
    "image": "assets/products/zerox.jpg",
    "packSizes": [
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "hexadhan-plus",
    "name": "Hexadhan Plus",
    "brand": "",
    "category": "",
    "image": "assets/products/hexadhan-plus.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "dhanucop",
    "name": "Dhanucop",
    "brand": "",
    "category": "",
    "image": "assets/products/dhanucop.jpg",
    "packSizes": [
      "500 gm",
      "25 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "dhanustin",
    "name": "Dhanustin",
    "brand": "",
    "category": "",
    "image": "assets/products/dhanustin.jpg",
    "packSizes": [
      "100 gm",
      "250 gm",
      "500 gm",
      "1 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "vitavax-power",
    "name": "Vitavax Power",
    "brand": "",
    "category": "",
    "image": "assets/products/vitavax-power.jpg",
    "packSizes": [
      "10 gm",
      "100 gm",
      "250 gm",
      "500 gm"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "dhanuka-m-45",
    "name": "Dhanuka M-45",
    "brand": "",
    "category": "",
    "image": "assets/products/dhanuka-m-45.jpg",
    "packSizes": [
      "100 gm",
      "250 gm",
      "500 gm",
      "1 kg"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "vitavax-ultra",
    "name": "Vitavax Ultra",
    "brand": "",
    "category": "",
    "image": "assets/products/vitavax-ultra.jpg",
    "packSizes": [
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "sheathmar",
    "name": "Sheathmar",
    "brand": "",
    "category": "",
    "image": "assets/products/sheathmar.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "spectrum",
    "name": "Spectrum",
    "brand": "",
    "category": "",
    "image": "assets/products/spectrum.jpg",
    "packSizes": [
      "100 ml",
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "sixer",
    "name": "Sixer",
    "brand": "",
    "category": "",
    "image": "assets/products/sixer.jpg",
    "packSizes": [
      "20 gm",
      "100 gm",
      "250 gm",
      "500 gm"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "kasu-b",
    "name": "Kasu-B",
    "brand": "",
    "category": "",
    "image": "assets/products/kasu-b.jpg",
    "packSizes": [
      "50 ml",
      "250 ml",
      "500 ml",
      "1 ltr"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "cursor",
    "name": "Cursor",
    "brand": "",
    "category": "",
    "image": "assets/products/cursor.jpg",
    "packSizes": [
      "50 ml",
      "100 ml",
      "250 ml"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  },
  {
    "id": "conika",
    "name": "Conika",
    "brand": "",
    "category": "",
    "image": "assets/products/conika.jpg",
    "packSizes": [
      "50 gm",
      "100 gm",
      "250 gm",
      "300 gm"
    ],
    "description": "",
    "status": "available",
    "price": null,
    "mrp": null,
    "sku": "",
    "manufacturer": "",
    "activeIngredient": "",
    "technicalDetails": "",
    "crops": [],
    "targetPests": [],
    "usage": "",
    "documents": []
  }
];
